/**
 * Tablet file schema
 */
export interface TabletSchema {
  /**
   * Schema version
   */
  version: string;

  /**
   * What version of the tool this schema was generated with
   *
   * Hashing algorithms may depend on the tool version, and the tool
   * will reject tablets generated by different versions.
   *
   * Since tablets are designed to be used as scratch space during a build, not
   * designed to be stored long-term, this limitation does not impact
   * usability.
   */
  toolVersion: string;

  /**
   * All the snippets in the tablet
   */
  snippets: {[key: string]: SnippetSchema};
}

/**
 * Schema for a snippet
 */
export interface SnippetSchema {
  /**
   * Translations for each individual language
   */
  translations: {[key: string]: TranslationSchema};
}

/**
 * A single snippet's translation
 */
export interface TranslationSchema {
  /**
   * The source of a single translation
   */
  source: string;
}