package software.amazon.jsii.tests.calculator

class `$Module`: software.amazon.jsii.JsiiModule("jsii-calc", "0.21.1", `$Module`::class.java, "jsii-calc@0.21.1.jsii.tgz") {
    override fun resolveClass(fqn: String?): Class<*> {
        return when (fqn) {
            "jsii-calc.AbstractClass" -> software.amazon.jsii.tests.calculator.AbstractClass::class.java
            "jsii-calc.AbstractClassBase" -> software.amazon.jsii.tests.calculator.AbstractClassBase::class.java
            "jsii-calc.AbstractClassReturner" -> software.amazon.jsii.tests.calculator.AbstractClassReturner::class.java
            "jsii-calc.AbstractSuite" -> software.amazon.jsii.tests.calculator.AbstractSuite::class.java
            "jsii-calc.Add" -> software.amazon.jsii.tests.calculator.Add::class.java
            "jsii-calc.AllTypes" -> software.amazon.jsii.tests.calculator.AllTypes::class.java
            "jsii-calc.AllTypesEnum" -> software.amazon.jsii.tests.calculator.AllTypesEnum::class.java
            "jsii-calc.AllowedMethodNames" -> software.amazon.jsii.tests.calculator.AllowedMethodNames::class.java
            "jsii-calc.AmbiguousParameters" -> software.amazon.jsii.tests.calculator.AmbiguousParameters::class.java
            "jsii-calc.AnonymousImplementationProvider" -> software.amazon.jsii.tests.calculator.AnonymousImplementationProvider::class.java
            "jsii-calc.AsyncVirtualMethods" -> software.amazon.jsii.tests.calculator.AsyncVirtualMethods::class.java
            "jsii-calc.AugmentableClass" -> software.amazon.jsii.tests.calculator.AugmentableClass::class.java
            "jsii-calc.BaseJsii976" -> software.amazon.jsii.tests.calculator.BaseJsii976::class.java
            "jsii-calc.Bell" -> software.amazon.jsii.tests.calculator.Bell::class.java
            "jsii-calc.BinaryOperation" -> software.amazon.jsii.tests.calculator.BinaryOperation::class.java
            "jsii-calc.Calculator" -> software.amazon.jsii.tests.calculator.Calculator::class.java
            "jsii-calc.CalculatorProps" -> software.amazon.jsii.tests.calculator.CalculatorProps::class.java
            "jsii-calc.ChildStruct982" -> software.amazon.jsii.tests.calculator.ChildStruct982::class.java
            "jsii-calc.ClassThatImplementsTheInternalInterface" -> software.amazon.jsii.tests.calculator.ClassThatImplementsTheInternalInterface::class.java
            "jsii-calc.ClassThatImplementsThePrivateInterface" -> software.amazon.jsii.tests.calculator.ClassThatImplementsThePrivateInterface::class.java
            "jsii-calc.ClassWithCollections" -> software.amazon.jsii.tests.calculator.ClassWithCollections::class.java
            "jsii-calc.ClassWithDocs" -> software.amazon.jsii.tests.calculator.ClassWithDocs::class.java
            "jsii-calc.ClassWithJavaReservedWords" -> software.amazon.jsii.tests.calculator.ClassWithJavaReservedWords::class.java
            "jsii-calc.ClassWithMutableObjectLiteralProperty" -> software.amazon.jsii.tests.calculator.ClassWithMutableObjectLiteralProperty::class.java
            "jsii-calc.ClassWithPrivateConstructorAndAutomaticProperties" -> software.amazon.jsii.tests.calculator.ClassWithPrivateConstructorAndAutomaticProperties::class.java
            "jsii-calc.ConfusingToJackson" -> software.amazon.jsii.tests.calculator.ConfusingToJackson::class.java
            "jsii-calc.ConfusingToJacksonStruct" -> software.amazon.jsii.tests.calculator.ConfusingToJacksonStruct::class.java
            "jsii-calc.ConstructorPassesThisOut" -> software.amazon.jsii.tests.calculator.ConstructorPassesThisOut::class.java
            "jsii-calc.Constructors" -> software.amazon.jsii.tests.calculator.Constructors::class.java
            "jsii-calc.ConsumePureInterface" -> software.amazon.jsii.tests.calculator.ConsumePureInterface::class.java
            "jsii-calc.ConsumerCanRingBell" -> software.amazon.jsii.tests.calculator.ConsumerCanRingBell::class.java
            "jsii-calc.ConsumersOfThisCrazyTypeSystem" -> software.amazon.jsii.tests.calculator.ConsumersOfThisCrazyTypeSystem::class.java
            "jsii-calc.DataRenderer" -> software.amazon.jsii.tests.calculator.DataRenderer::class.java
            "jsii-calc.DefaultedConstructorArgument" -> software.amazon.jsii.tests.calculator.DefaultedConstructorArgument::class.java
            "jsii-calc.Demonstrate982" -> software.amazon.jsii.tests.calculator.Demonstrate982::class.java
            "jsii-calc.DeprecatedClass" -> software.amazon.jsii.tests.calculator.DeprecatedClass::class.java
            "jsii-calc.DeprecatedEnum" -> software.amazon.jsii.tests.calculator.DeprecatedEnum::class.java
            "jsii-calc.DeprecatedStruct" -> software.amazon.jsii.tests.calculator.DeprecatedStruct::class.java
            "jsii-calc.DerivedClassHasNoProperties.Base" -> software.amazon.jsii.tests.calculator.DerivedClassHasNoProperties.Base::class.java
            "jsii-calc.DerivedClassHasNoProperties.Derived" -> software.amazon.jsii.tests.calculator.DerivedClassHasNoProperties.Derived::class.java
            "jsii-calc.DerivedStruct" -> software.amazon.jsii.tests.calculator.DerivedStruct::class.java
            "jsii-calc.DiamondInheritanceBaseLevelStruct" -> software.amazon.jsii.tests.calculator.DiamondInheritanceBaseLevelStruct::class.java
            "jsii-calc.DiamondInheritanceFirstMidLevelStruct" -> software.amazon.jsii.tests.calculator.DiamondInheritanceFirstMidLevelStruct::class.java
            "jsii-calc.DiamondInheritanceSecondMidLevelStruct" -> software.amazon.jsii.tests.calculator.DiamondInheritanceSecondMidLevelStruct::class.java
            "jsii-calc.DiamondInheritanceTopLevelStruct" -> software.amazon.jsii.tests.calculator.DiamondInheritanceTopLevelStruct::class.java
            "jsii-calc.DisappointingCollectionSource" -> software.amazon.jsii.tests.calculator.DisappointingCollectionSource::class.java
            "jsii-calc.DoNotOverridePrivates" -> software.amazon.jsii.tests.calculator.DoNotOverridePrivates::class.java
            "jsii-calc.DoNotRecognizeAnyAsOptional" -> software.amazon.jsii.tests.calculator.DoNotRecognizeAnyAsOptional::class.java
            "jsii-calc.DocumentedClass" -> software.amazon.jsii.tests.calculator.DocumentedClass::class.java
            "jsii-calc.DontComplainAboutVariadicAfterOptional" -> software.amazon.jsii.tests.calculator.DontComplainAboutVariadicAfterOptional::class.java
            "jsii-calc.DoubleTrouble" -> software.amazon.jsii.tests.calculator.DoubleTrouble::class.java
            "jsii-calc.EnumDispenser" -> software.amazon.jsii.tests.calculator.EnumDispenser::class.java
            "jsii-calc.EraseUndefinedHashValues" -> software.amazon.jsii.tests.calculator.EraseUndefinedHashValues::class.java
            "jsii-calc.EraseUndefinedHashValuesOptions" -> software.amazon.jsii.tests.calculator.EraseUndefinedHashValuesOptions::class.java
            "jsii-calc.ExperimentalClass" -> software.amazon.jsii.tests.calculator.ExperimentalClass::class.java
            "jsii-calc.ExperimentalEnum" -> software.amazon.jsii.tests.calculator.ExperimentalEnum::class.java
            "jsii-calc.ExperimentalStruct" -> software.amazon.jsii.tests.calculator.ExperimentalStruct::class.java
            "jsii-calc.ExportedBaseClass" -> software.amazon.jsii.tests.calculator.ExportedBaseClass::class.java
            "jsii-calc.ExtendsInternalInterface" -> software.amazon.jsii.tests.calculator.ExtendsInternalInterface::class.java
            "jsii-calc.GiveMeStructs" -> software.amazon.jsii.tests.calculator.GiveMeStructs::class.java
            "jsii-calc.Greetee" -> software.amazon.jsii.tests.calculator.Greetee::class.java
            "jsii-calc.GreetingAugmenter" -> software.amazon.jsii.tests.calculator.GreetingAugmenter::class.java
            "jsii-calc.IAnonymousImplementationProvider" -> software.amazon.jsii.tests.calculator.IAnonymousImplementationProvider::class.java
            "jsii-calc.IAnonymouslyImplementMe" -> software.amazon.jsii.tests.calculator.IAnonymouslyImplementMe::class.java
            "jsii-calc.IAnotherPublicInterface" -> software.amazon.jsii.tests.calculator.IAnotherPublicInterface::class.java
            "jsii-calc.IBell" -> software.amazon.jsii.tests.calculator.IBell::class.java
            "jsii-calc.IBellRinger" -> software.amazon.jsii.tests.calculator.IBellRinger::class.java
            "jsii-calc.IConcreteBellRinger" -> software.amazon.jsii.tests.calculator.IConcreteBellRinger::class.java
            "jsii-calc.IDeprecatedInterface" -> software.amazon.jsii.tests.calculator.IDeprecatedInterface::class.java
            "jsii-calc.IExperimentalInterface" -> software.amazon.jsii.tests.calculator.IExperimentalInterface::class.java
            "jsii-calc.IExtendsPrivateInterface" -> software.amazon.jsii.tests.calculator.IExtendsPrivateInterface::class.java
            "jsii-calc.IFriendlier" -> software.amazon.jsii.tests.calculator.IFriendlier::class.java
            "jsii-calc.IFriendlyRandomGenerator" -> software.amazon.jsii.tests.calculator.IFriendlyRandomGenerator::class.java
            "jsii-calc.IInterfaceImplementedByAbstractClass" -> software.amazon.jsii.tests.calculator.IInterfaceImplementedByAbstractClass::class.java
            "jsii-calc.IInterfaceThatShouldNotBeADataType" -> software.amazon.jsii.tests.calculator.IInterfaceThatShouldNotBeADataType::class.java
            "jsii-calc.IInterfaceWithInternal" -> software.amazon.jsii.tests.calculator.IInterfaceWithInternal::class.java
            "jsii-calc.IInterfaceWithMethods" -> software.amazon.jsii.tests.calculator.IInterfaceWithMethods::class.java
            "jsii-calc.IInterfaceWithOptionalMethodArguments" -> software.amazon.jsii.tests.calculator.IInterfaceWithOptionalMethodArguments::class.java
            "jsii-calc.IInterfaceWithProperties" -> software.amazon.jsii.tests.calculator.IInterfaceWithProperties::class.java
            "jsii-calc.IInterfaceWithPropertiesExtension" -> software.amazon.jsii.tests.calculator.IInterfaceWithPropertiesExtension::class.java
            "jsii-calc.IJSII417Derived" -> software.amazon.jsii.tests.calculator.IJSII417Derived::class.java
            "jsii-calc.IJSII417PublicBaseOfBase" -> software.amazon.jsii.tests.calculator.IJSII417PublicBaseOfBase::class.java
            "jsii-calc.IJsii487External" -> software.amazon.jsii.tests.calculator.IJsii487External::class.java
            "jsii-calc.IJsii487External2" -> software.amazon.jsii.tests.calculator.IJsii487External2::class.java
            "jsii-calc.IJsii496" -> software.amazon.jsii.tests.calculator.IJsii496::class.java
            "jsii-calc.IMutableObjectLiteral" -> software.amazon.jsii.tests.calculator.IMutableObjectLiteral::class.java
            "jsii-calc.INonInternalInterface" -> software.amazon.jsii.tests.calculator.INonInternalInterface::class.java
            "jsii-calc.IObjectWithProperty" -> software.amazon.jsii.tests.calculator.IObjectWithProperty::class.java
            "jsii-calc.IPrivatelyImplemented" -> software.amazon.jsii.tests.calculator.IPrivatelyImplemented::class.java
            "jsii-calc.IPublicInterface" -> software.amazon.jsii.tests.calculator.IPublicInterface::class.java
            "jsii-calc.IPublicInterface2" -> software.amazon.jsii.tests.calculator.IPublicInterface2::class.java
            "jsii-calc.IRandomNumberGenerator" -> software.amazon.jsii.tests.calculator.IRandomNumberGenerator::class.java
            "jsii-calc.IReturnJsii976" -> software.amazon.jsii.tests.calculator.IReturnJsii976::class.java
            "jsii-calc.IReturnsNumber" -> software.amazon.jsii.tests.calculator.IReturnsNumber::class.java
            "jsii-calc.IStableInterface" -> software.amazon.jsii.tests.calculator.IStableInterface::class.java
            "jsii-calc.IStructReturningDelegate" -> software.amazon.jsii.tests.calculator.IStructReturningDelegate::class.java
            "jsii-calc.ImplementInternalInterface" -> software.amazon.jsii.tests.calculator.ImplementInternalInterface::class.java
            "jsii-calc.Implementation" -> software.amazon.jsii.tests.calculator.Implementation::class.java
            "jsii-calc.ImplementsInterfaceWithInternal" -> software.amazon.jsii.tests.calculator.ImplementsInterfaceWithInternal::class.java
            "jsii-calc.ImplementsInterfaceWithInternalSubclass" -> software.amazon.jsii.tests.calculator.ImplementsInterfaceWithInternalSubclass::class.java
            "jsii-calc.ImplementsPrivateInterface" -> software.amazon.jsii.tests.calculator.ImplementsPrivateInterface::class.java
            "jsii-calc.ImplictBaseOfBase" -> software.amazon.jsii.tests.calculator.ImplictBaseOfBase::class.java
            "jsii-calc.InbetweenClass" -> software.amazon.jsii.tests.calculator.InbetweenClass::class.java
            "jsii-calc.InterfaceInNamespaceIncludesClasses.Foo" -> software.amazon.jsii.tests.calculator.InterfaceInNamespaceIncludesClasses.Foo::class.java
            "jsii-calc.InterfaceInNamespaceIncludesClasses.Hello" -> software.amazon.jsii.tests.calculator.InterfaceInNamespaceIncludesClasses.Hello::class.java
            "jsii-calc.InterfaceInNamespaceOnlyInterface.Hello" -> software.amazon.jsii.tests.calculator.InterfaceInNamespaceOnlyInterface.Hello::class.java
            "jsii-calc.InterfacesMaker" -> software.amazon.jsii.tests.calculator.InterfacesMaker::class.java
            "jsii-calc.JSII417Derived" -> software.amazon.jsii.tests.calculator.JSII417Derived::class.java
            "jsii-calc.JSII417PublicBaseOfBase" -> software.amazon.jsii.tests.calculator.JSII417PublicBaseOfBase::class.java
            "jsii-calc.JSObjectLiteralForInterface" -> software.amazon.jsii.tests.calculator.JSObjectLiteralForInterface::class.java
            "jsii-calc.JSObjectLiteralToNative" -> software.amazon.jsii.tests.calculator.JSObjectLiteralToNative::class.java
            "jsii-calc.JSObjectLiteralToNativeClass" -> software.amazon.jsii.tests.calculator.JSObjectLiteralToNativeClass::class.java
            "jsii-calc.JavaReservedWords" -> software.amazon.jsii.tests.calculator.JavaReservedWords::class.java
            "jsii-calc.Jsii487Derived" -> software.amazon.jsii.tests.calculator.Jsii487Derived::class.java
            "jsii-calc.Jsii496Derived" -> software.amazon.jsii.tests.calculator.Jsii496Derived::class.java
            "jsii-calc.JsiiAgent" -> software.amazon.jsii.tests.calculator.JsiiAgent::class.java
            "jsii-calc.JsonFormatter" -> software.amazon.jsii.tests.calculator.JsonFormatter::class.java
            "jsii-calc.LoadBalancedFargateServiceProps" -> software.amazon.jsii.tests.calculator.LoadBalancedFargateServiceProps::class.java
            "jsii-calc.MethodNamedProperty" -> software.amazon.jsii.tests.calculator.MethodNamedProperty::class.java
            "jsii-calc.Multiply" -> software.amazon.jsii.tests.calculator.Multiply::class.java
            "jsii-calc.Negate" -> software.amazon.jsii.tests.calculator.Negate::class.java
            "jsii-calc.NestedStruct" -> software.amazon.jsii.tests.calculator.NestedStruct::class.java
            "jsii-calc.NodeStandardLibrary" -> software.amazon.jsii.tests.calculator.NodeStandardLibrary::class.java
            "jsii-calc.NullShouldBeTreatedAsUndefined" -> software.amazon.jsii.tests.calculator.NullShouldBeTreatedAsUndefined::class.java
            "jsii-calc.NullShouldBeTreatedAsUndefinedData" -> software.amazon.jsii.tests.calculator.NullShouldBeTreatedAsUndefinedData::class.java
            "jsii-calc.NumberGenerator" -> software.amazon.jsii.tests.calculator.NumberGenerator::class.java
            "jsii-calc.ObjectRefsInCollections" -> software.amazon.jsii.tests.calculator.ObjectRefsInCollections::class.java
            "jsii-calc.ObjectWithPropertyProvider" -> software.amazon.jsii.tests.calculator.ObjectWithPropertyProvider::class.java
            "jsii-calc.Old" -> software.amazon.jsii.tests.calculator.Old::class.java
            "jsii-calc.OptionalArgumentInvoker" -> software.amazon.jsii.tests.calculator.OptionalArgumentInvoker::class.java
            "jsii-calc.OptionalConstructorArgument" -> software.amazon.jsii.tests.calculator.OptionalConstructorArgument::class.java
            "jsii-calc.OptionalStruct" -> software.amazon.jsii.tests.calculator.OptionalStruct::class.java
            "jsii-calc.OptionalStructConsumer" -> software.amazon.jsii.tests.calculator.OptionalStructConsumer::class.java
            "jsii-calc.OverridableProtectedMember" -> software.amazon.jsii.tests.calculator.OverridableProtectedMember::class.java
            "jsii-calc.OverrideReturnsObject" -> software.amazon.jsii.tests.calculator.OverrideReturnsObject::class.java
            "jsii-calc.ParentStruct982" -> software.amazon.jsii.tests.calculator.ParentStruct982::class.java
            "jsii-calc.PartiallyInitializedThisConsumer" -> software.amazon.jsii.tests.calculator.PartiallyInitializedThisConsumer::class.java
            "jsii-calc.Polymorphism" -> software.amazon.jsii.tests.calculator.Polymorphism::class.java
            "jsii-calc.Power" -> software.amazon.jsii.tests.calculator.Power::class.java
            "jsii-calc.PropertyNamedProperty" -> software.amazon.jsii.tests.calculator.PropertyNamedProperty::class.java
            "jsii-calc.PublicClass" -> software.amazon.jsii.tests.calculator.PublicClass::class.java
            "jsii-calc.PythonReservedWords" -> software.amazon.jsii.tests.calculator.PythonReservedWords::class.java
            "jsii-calc.ReferenceEnumFromScopedPackage" -> software.amazon.jsii.tests.calculator.ReferenceEnumFromScopedPackage::class.java
            "jsii-calc.ReturnsPrivateImplementationOfInterface" -> software.amazon.jsii.tests.calculator.ReturnsPrivateImplementationOfInterface::class.java
            "jsii-calc.RootStruct" -> software.amazon.jsii.tests.calculator.RootStruct::class.java
            "jsii-calc.RootStructValidator" -> software.amazon.jsii.tests.calculator.RootStructValidator::class.java
            "jsii-calc.RuntimeTypeChecking" -> software.amazon.jsii.tests.calculator.RuntimeTypeChecking::class.java
            "jsii-calc.SecondLevelStruct" -> software.amazon.jsii.tests.calculator.SecondLevelStruct::class.java
            "jsii-calc.SingleInstanceTwoTypes" -> software.amazon.jsii.tests.calculator.SingleInstanceTwoTypes::class.java
            "jsii-calc.SingletonInt" -> software.amazon.jsii.tests.calculator.SingletonInt::class.java
            "jsii-calc.SingletonIntEnum" -> software.amazon.jsii.tests.calculator.SingletonIntEnum::class.java
            "jsii-calc.SingletonString" -> software.amazon.jsii.tests.calculator.SingletonString::class.java
            "jsii-calc.SingletonStringEnum" -> software.amazon.jsii.tests.calculator.SingletonStringEnum::class.java
            "jsii-calc.SmellyStruct" -> software.amazon.jsii.tests.calculator.SmellyStruct::class.java
            "jsii-calc.SomeTypeJsii976" -> software.amazon.jsii.tests.calculator.SomeTypeJsii976::class.java
            "jsii-calc.StableClass" -> software.amazon.jsii.tests.calculator.StableClass::class.java
            "jsii-calc.StableEnum" -> software.amazon.jsii.tests.calculator.StableEnum::class.java
            "jsii-calc.StableStruct" -> software.amazon.jsii.tests.calculator.StableStruct::class.java
            "jsii-calc.StaticContext" -> software.amazon.jsii.tests.calculator.StaticContext::class.java
            "jsii-calc.Statics" -> software.amazon.jsii.tests.calculator.Statics::class.java
            "jsii-calc.StringEnum" -> software.amazon.jsii.tests.calculator.StringEnum::class.java
            "jsii-calc.StripInternal" -> software.amazon.jsii.tests.calculator.StripInternal::class.java
            "jsii-calc.StructA" -> software.amazon.jsii.tests.calculator.StructA::class.java
            "jsii-calc.StructB" -> software.amazon.jsii.tests.calculator.StructB::class.java
            "jsii-calc.StructParameterType" -> software.amazon.jsii.tests.calculator.StructParameterType::class.java
            "jsii-calc.StructPassing" -> software.amazon.jsii.tests.calculator.StructPassing::class.java
            "jsii-calc.StructUnionConsumer" -> software.amazon.jsii.tests.calculator.StructUnionConsumer::class.java
            "jsii-calc.StructWithJavaReservedWords" -> software.amazon.jsii.tests.calculator.StructWithJavaReservedWords::class.java
            "jsii-calc.Sum" -> software.amazon.jsii.tests.calculator.Sum::class.java
            "jsii-calc.SupportsNiceJavaBuilder" -> software.amazon.jsii.tests.calculator.SupportsNiceJavaBuilder::class.java
            "jsii-calc.SupportsNiceJavaBuilderProps" -> software.amazon.jsii.tests.calculator.SupportsNiceJavaBuilderProps::class.java
            "jsii-calc.SupportsNiceJavaBuilderWithRequiredProps" -> software.amazon.jsii.tests.calculator.SupportsNiceJavaBuilderWithRequiredProps::class.java
            "jsii-calc.SyncVirtualMethods" -> software.amazon.jsii.tests.calculator.SyncVirtualMethods::class.java
            "jsii-calc.Thrower" -> software.amazon.jsii.tests.calculator.Thrower::class.java
            "jsii-calc.TopLevelStruct" -> software.amazon.jsii.tests.calculator.TopLevelStruct::class.java
            "jsii-calc.UnaryOperation" -> software.amazon.jsii.tests.calculator.UnaryOperation::class.java
            "jsii-calc.UnionProperties" -> software.amazon.jsii.tests.calculator.UnionProperties::class.java
            "jsii-calc.UseBundledDependency" -> software.amazon.jsii.tests.calculator.UseBundledDependency::class.java
            "jsii-calc.UseCalcBase" -> software.amazon.jsii.tests.calculator.UseCalcBase::class.java
            "jsii-calc.UsesInterfaceWithProperties" -> software.amazon.jsii.tests.calculator.UsesInterfaceWithProperties::class.java
            "jsii-calc.VariadicInvoker" -> software.amazon.jsii.tests.calculator.VariadicInvoker::class.java
            "jsii-calc.VariadicMethod" -> software.amazon.jsii.tests.calculator.VariadicMethod::class.java
            "jsii-calc.VirtualMethodPlayground" -> software.amazon.jsii.tests.calculator.VirtualMethodPlayground::class.java
            "jsii-calc.VoidCallback" -> software.amazon.jsii.tests.calculator.VoidCallback::class.java
            "jsii-calc.WithPrivatePropertyInConstructor" -> software.amazon.jsii.tests.calculator.WithPrivatePropertyInConstructor::class.java
            "jsii-calc.composition.CompositeOperation" -> software.amazon.jsii.tests.calculator.composition.CompositeOperation::class.java
            else -> throw ClassNotFoundException("Unknown JSII type: $fqn")
        }
    }
}
